"""
database.py - The Memory Layer
Manages SQLite state for all tasks, artifacts, and logs.
"""

from sqlalchemy import create_engine, Column, String, DateTime, ForeignKey, JSON, Float, Boolean, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, scoped_session
from datetime import datetime
import uuid
import os
import time
from typing import Any, Optional, Dict, List
from utils.logger import logger

Base = declarative_base()


class TaskRecord(Base):
    """Stores the lifecycle of a task from request to completion."""
    __tablename__ = 'tasks'

    task_id = Column(String, primary_key=True)
    priority = Column(String, default="medium")
    agent_role = Column(String)
    action = Column(String)
    status = Column(String, default="pending")
    payload = Column(JSON)
    constraints = Column(JSON)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)
    escalated_to_cloud = Column(Boolean, default=False)
    parent_task_id = Column(String, nullable=True)

    artifacts = relationship("ArtifactRecord", back_populates="task")
    logs = relationship("LogRecord", back_populates="task")
    metrics = relationship("ExecutionMetricsRecord", back_populates="task")
    dag_optimizations = relationship("DAGOptimizationRecord", back_populates="task")


class ArtifactRecord(Base):
    """Stores the output generated by agents for a specific task."""
    __tablename__ = 'artifacts'

    artifact_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id = Column(String, ForeignKey('tasks.task_id'))
    content = Column(JSON)
    confidence = Column(Float, default=0.0)
    meta = Column(JSON)
    created_at = Column(DateTime, default=datetime.now)

    task = relationship("TaskRecord", back_populates="artifacts")


class LogRecord(Base):
    """Audit log of all task transitions."""
    __tablename__ = 'logs'

    log_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id = Column(String, ForeignKey('tasks.task_id'))
    old_status = Column(String)
    new_status = Column(String)
    reason = Column(String)
    created_at = Column(DateTime, default=datetime.now)

    task = relationship("TaskRecord", back_populates="logs")


class ConversationMemory(Base):
    """Stores chat history for session-based memory."""
    __tablename__ = 'conversation_memory'

    memory_id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String, index=True)
    role = Column(String) # 'user' or 'assistant'
    content = Column(String)
    timestamp = Column(DateTime, default=datetime.now)


class UserPreference(Base):
    """Phase 7.3: Stores long-term user preferences and style guides."""
    __tablename__ = 'user_preferences'

    pref_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, index=True)
    category = Column(String)  # e.g., 'tone', 'visual', 'constraints'
    preference_key = Column(String) # e.g., 'favorite_color'
    preference_value = Column(String)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)


class ExecutionMetricsRecord(Base):
    """Phase 7.2: Stores execution metrics for DAG optimization and feedback loop."""
    __tablename__ = 'execution_metrics'

    metric_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id = Column(String, ForeignKey('tasks.task_id'), index=True)
    step_number = Column(Integer)
    agent_role = Column(String)
    action = Column(String)
    duration_seconds = Column(Float)
    prompt_tokens = Column(Integer)
    completion_tokens = Column(Integer)
    total_tokens = Column(Integer)
    success = Column(Boolean)
    dependencies = Column(JSON)  # List of step numbers this depends on
    parallelizable_with = Column(JSON)  # List of step numbers that can run in parallel
    meta = Column(JSON)  # Additional metadata
    created_at = Column(DateTime, default=datetime.now, index=True)

    task = relationship("TaskRecord", back_populates="metrics")


class DAGOptimizationRecord(Base):
    """Phase 7.2: Stores suggested DAG optimizations from Meta-Brain."""
    __tablename__ = 'dag_optimizations'

    optimization_id = Column(String, primary_key=True)
    task_id = Column(String, ForeignKey('tasks.task_id'), nullable=True)
    dag_id = Column(String, index=True)
    optimization_type = Column(String)  # "reorder", "consolidate", "parallelize", "split"
    current_order = Column(JSON)
    suggested_order = Column(JSON)
    reason = Column(String)
    estimated_speedup = Column(Float)  # 0.0-1.0
    estimated_token_savings = Column(Integer)
    confidence = Column(Float)  # 0.0-1.0
    success_history = Column(Integer)  # Number of successful applications
    applied = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.now, index=True)

    task = relationship("TaskRecord", back_populates="dag_optimizations")


class AppointmentRecord(Base):
    """Stores appointment booking information."""
    __tablename__ = 'appointments'

    appointment_id = Column(String, primary_key=True)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    email = Column(String, nullable=True)
    appointment_type = Column(String, default="consultation")  # consultation, treatment, follow_up, other
    preferred_date = Column(String, nullable=False)  # YYYY-MM-DD
    preferred_time = Column(String, nullable=False)  # HH:MM
    notes = Column(String, nullable=True)
    status = Column(String, default="pending")  # pending, confirmed, completed, cancelled, no_show
    created_by_session = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.now, index=True)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now, index=True)
    confirmed_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)


class AppointmentCollectionStateRecord(Base):
    """Tracks multi-turn appointment collection state."""
    __tablename__ = 'appointment_collection_states'

    state_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, index=True, nullable=False)
    current_step = Column(Integer, default=0)
    collected_data = Column(JSON, default={})
    steps_config = Column(JSON)  # Store the steps definition
    is_complete = Column(Boolean, default=False)
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), nullable=True)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    appointment = relationship("AppointmentRecord")


class DepartmentRecord(Base):
    """Stores clinic/department information."""
    __tablename__ = 'departments'

    department_id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class AccountingRecord(Base):
    """Stores parsed accounting summaries from transfer slips and invoices."""
    __tablename__ = 'accounting_entries'

    entry_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    file_path = Column(String, nullable=False)
    document_type = Column(String, nullable=True)
    transaction_date = Column(String, nullable=True)
    amount = Column(String, nullable=True)
    sender = Column(String, nullable=True)
    recipient = Column(String, nullable=True)
    reference = Column(String, nullable=True)
    summary = Column(String, nullable=True)
    extracted_text = Column(String, nullable=True)
    metadata_json = Column(JSON, default={})
    created_at = Column(DateTime, default=datetime.now, index=True)


class ServiceTypeRecord(Base):
    """Stores appointment service types."""
    __tablename__ = 'service_types'

    service_id = Column(String, primary_key=True)
    department_id = Column(String, ForeignKey('departments.department_id'))
    name = Column(String, nullable=False)
    duration_minutes = Column(Integer, default=30)
    description = Column(String, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class AppointmentSlotRecord(Base):
    """Stores available appointment slots."""
    __tablename__ = 'appointment_slots'

    slot_id = Column(String, primary_key=True)
    department_id = Column(String, ForeignKey('departments.department_id'))
    date = Column(String, index=True)  # YYYY-MM-DD
    start_time = Column(String)  # HH:MM
    end_time = Column(String)  # HH:MM
    capacity = Column(Integer, default=1)
    booked_count = Column(Integer, default=0)
    is_available = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class NotificationRecord(Base):
    """Stores notification history (SMS/Email)."""
    __tablename__ = 'notifications'

    notification_id = Column(String, primary_key=True)
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), index=True)
    notification_type = Column(String)  # sms_confirmation, email_confirmation, etc.
    recipient = Column(String)  # Phone number or email
    message = Column(String)
    sent_at = Column(DateTime, nullable=True)
    delivery_status = Column(String, default='pending')  # pending, sent, failed
    retry_count = Column(Integer, default=0)
    error_message = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class ReschedulingRecord(Base):
    """Tracks appointment rescheduling requests."""
    __tablename__ = 'rescheduling_requests'

    reschedule_id = Column(String, primary_key=True)
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), index=True)
    original_date = Column(String)
    original_time = Column(String)
    new_date = Column(String)
    new_time = Column(String)
    reason = Column(String)  # customer_request, conflict, admin_request, etc.
    reason_notes = Column(String, nullable=True)
    requested_by = Column(String, default='customer')
    status = Column(String, default='pending')  # pending, approved, rejected
    approved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class CancellationRecord(Base):
    """Tracks appointment cancellations."""
    __tablename__ = 'cancellations'

    cancellation_id = Column(String, primary_key=True)
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), index=True)
    reason = Column(String)  # customer_request, admin_request, no_show, etc.
    reason_notes = Column(String, nullable=True)
    cancelled_by = Column(String, default='customer')
    refund_eligible = Column(Boolean, default=True)
    cancelled_at = Column(DateTime, default=datetime.now)
    created_at = Column(DateTime, default=datetime.now, index=True)


class AppointmentHistoryRecord(Base):
    """Stores appointment history for customers."""
    __tablename__ = 'appointment_history'

    history_id = Column(String, primary_key=True)
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), index=True)
    phone_number = Column(String, index=True)
    event_type = Column(String)  # booked, rescheduled, cancelled, completed, no_show
    event_date = Column(DateTime, default=datetime.now)
    notes = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.now, index=True)


class AdminApprovalRecord(Base):
    """Stores admin approval/rejection for appointments."""
    __tablename__ = 'admin_approvals'

    approval_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    appointment_id = Column(String, ForeignKey('appointments.appointment_id'), index=True)
    admin_id = Column(String, nullable=False)
    decision = Column(String, nullable=False)  # 'approved', 'rejected'
    reason = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.now)

    appointment = relationship("AppointmentRecord")


class AgentConfigRecord(Base):
    """Stores persistent system prompts and hyperparameters for agents."""
    __tablename__ = 'agent_configs'

    agent_role = Column(String, primary_key=True)
    system_prompt = Column(String, nullable=False)
    temperature = Column(Float, default=0.7)
    max_tokens = Column(Integer, default=2000)
    version = Column(Integer, default=1)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)


class DBManager:
    """Singleton manager to handle SQLite sessions with thread-safe scoped sessions."""

    def __init__(self, db_url: str = None):
        if db_url is None:
            db_path = os.path.join(os.path.dirname(__file__), 'agent_system.db')
            db_url = f"sqlite:///{db_path}"

        self.engine = create_engine(db_url, echo=False, connect_args={"check_same_thread": False})
        Base.metadata.create_all(self.engine)
        
        # Phase 8: Optimization - Use scoped_session for thread-safety in async environments
        self.SessionFactory = sessionmaker(bind=self.engine)
        self.Session = scoped_session(self.SessionFactory)
        
        # Simple In-Memory Cache for frequent queries
        self._cache = {}
        self._cache_ttl = 300  # Cache expires in 5 minutes

    def _get_cached(self, key: str) -> Optional[Any]:
        """Retrieves item from cache if not expired."""
        if key in self._cache:
            val, timestamp = self._cache[key]
            if time.time() - timestamp < self._cache_ttl:
                return val
        return None

    def _set_cache(self, key: str, value: Any):
        """Stores item in cache with current timestamp."""
        self._cache[key] = (value, time.time())

    def clear_cache(self):
        """Clears all cached data."""
        self._cache = {}

    def save_message(self, session_id: str, role: str, content: str):
        """Saves a message to the conversation history."""
        session = self.Session()
        try:
            msg = ConversationMemory(session_id=session_id, role=role, content=content)
            session.add(msg)
            session.commit()
        except Exception as e:
            logger.error(f"Failed to save message: {e}")
            session.rollback()
        finally:
            self.Session.remove() # Crucial for scoped_session

    def get_history(self, session_id: str, limit: int = 10) -> List[Dict[str, str]]:
        """Retrieves the last N messages for a session."""
        session = self.Session()
        try:
            history = session.query(ConversationMemory)\
                .filter(ConversationMemory.session_id == session_id)\
                .order_by(ConversationMemory.timestamp.desc())\
                .limit(limit).all()
            return [{"role": h.role, "content": h.content} for h in reversed(history)]
        finally:
            self.Session.remove()

    def _validate_payload(self, payload: dict) -> bool:
        """Validate that payload has required fields."""
        if not isinstance(payload, dict):
            raise ValueError(f"Payload must be a dict, got {type(payload).__name__}")
        if not payload:
            raise ValueError("Payload cannot be empty")
        # Payload should have 'instruction' or 'user_input' for most tasks
        if 'instruction' not in payload and 'user_input' not in payload and 'content' not in payload:
            # Allow payloads without instruction for special cases (monitoring, etc.)
            logger.warning(f"⚠️ Payload lacks standard fields: {list(payload.keys())}")
        return True

    def _validate_artifacts(self, artifact_data: dict) -> bool:
        """Validate that artifacts have required structure."""
        if not isinstance(artifact_data, dict):
            raise ValueError(f"Artifact must be a dict, got {type(artifact_data).__name__}")
        artifacts = artifact_data.get('artifacts')
        if artifacts is None:
            raise ValueError("Artifacts field is required")
        if not artifacts and not isinstance(artifacts, dict):
            raise ValueError(f"Artifacts must be a dict, got {type(artifacts).__name__}")
        return True

    def create_task(self, task_data: dict) -> str:
        """Creates a new task record in the database."""
        session = self.Session()
        try:
            # Validate payload before saving
            payload = task_data.get('payload', {})
            self._validate_payload(payload)
            
            task_id = task_data.get('task_id', str(uuid.uuid4()))
            new_task = TaskRecord(
                task_id=task_id,
                priority=task_data.get('priority', 'medium'),
                agent_role=task_data.get('agent_role'),
                action=task_data.get('action'),
                payload=payload,
                constraints=task_data.get('constraints', []),
                status=task_data.get('status', 'pending'),
                escalated_to_cloud=task_data.get('escalated_to_cloud', False),
                parent_task_id=task_data.get('parent_task_id')
            )
            session.add(new_task)
            session.commit()
            logger.info(f"✓ Task created | ID: {task_id} | Agent: {task_data.get('agent_role')}")
            return task_id
        except Exception as e:
            session.rollback()
            logger.error(f"❌ Failed to create task: {str(e)}")
            raise
        finally:
            self.Session.remove()

    def update_task_status(self, task_id: str, status: str, reason: str = None):
        """Updates the status of a task and logs the transition."""
        session = self.Session()
        try:
            task = session.query(TaskRecord).filter_by(task_id=task_id).first()
            if task:
                old_status = task.status
                task.status = status
                session.commit()

                # Log the transition
                log = LogRecord(
                    log_id=str(uuid.uuid4()),
                    task_id=task_id,
                    old_status=old_status,
                    new_status=status,
                    reason=reason or "Status update"
                )
                session.add(log)
                session.commit()
        except Exception as e:
            logger.error(f"Failed to update task status for {task_id}: {e}")
            session.rollback()
        finally:
            self.Session.remove()

    def save_artifact(self, task_id: str, artifact_data: dict):
        """Saves the result of an agent's work."""
        session = self.Session()
        try:
            # Validate artifacts before saving
            self._validate_artifacts(artifact_data)
            
            artifact = ArtifactRecord(
                artifact_id=str(uuid.uuid4()),
                task_id=task_id,
                content=artifact_data.get('artifacts'),
                confidence=artifact_data.get('meta', {}).get('confidence', 0.0),
                meta=artifact_data.get('meta')
            )
            session.add(artifact)
            session.commit()
            logger.info(f"✓ Artifact saved | Task: {task_id} | Confidence: {artifact.confidence:.2f}")
        except Exception as e:
            session.rollback()
            logger.error(f"❌ Failed to save artifact for task {task_id}: {str(e)}")
            raise
        finally:
            self.Session.remove()

    def save_accounting_entry(self, entry_data: dict) -> str:
        """Saves a structured accounting entry for transfer slips and invoices."""
        session = self.Session()
        try:
            entry = AccountingRecord(
                entry_id=str(uuid.uuid4()),
                file_path=entry_data.get('file_path', ''),
                document_type=entry_data.get('document_type'),
                transaction_date=entry_data.get('transaction_date'),
                amount=entry_data.get('amount'),
                sender=entry_data.get('sender'),
                recipient=entry_data.get('recipient'),
                reference=entry_data.get('reference'),
                summary=entry_data.get('summary'),
                extracted_text=entry_data.get('extracted_text'),
                metadata_json=entry_data.get('metadata', {})
            )
            session.add(entry)
            session.commit()
            entry_id = entry.entry_id
            return entry_id
        except Exception as e:
            session.rollback()
            logger.error(f"Failed to save accounting entry: {e}")
            raise
        finally:
            self.Session.remove()

    def get_accounting_entries(self, limit: int = 50) -> list:
        """Retrieves recently stored accounting entries."""
        session = self.Session()
        try:
            entries = session.query(AccountingRecord).order_by(AccountingRecord.created_at.desc()).limit(limit).all()
            return entries
        finally:
            self.Session.remove()

    def get_task(self, task_id: str) -> TaskRecord:
        """Retrieves a task record with caching."""
        session = self.Session()
        task = session.query(TaskRecord).filter_by(task_id=task_id).first()
        session.close()
        return task

    def get_agent_config(self, agent_role: str) -> Optional[Dict[str, Any]]:
        """Retrieves the persistent configuration for a specific agent role."""
        cache_key = f"config_{agent_role}"
        cached = self._get_cached(cache_key)
        if cached:
            return cached

        session = self.Session()
        try:
            config = session.query(AgentConfigRecord).filter_by(agent_role=agent_role).first()
            if config:
                res = {
                    "agent_role": config.agent_role,
                    "system_prompt": config.system_prompt,
                    "temperature": config.temperature,
                    "max_tokens": config.max_tokens,
                    "version": config.version,
                    "updated_at": config.updated_at.isoformat() if config.updated_at else None
                }
                self._set_cache(cache_key, res)
                return res
            return None
        finally:
            session.close()

    def save_agent_config(self, agent_role: str, system_prompt: str, temperature: float = 0.7, max_tokens: int = 2000):
        """Saves or updates an agent's configuration and increments version."""
        session = self.Session()
        try:
            config = session.query(AgentConfigRecord).filter_by(agent_role=agent_role).first()
            if config:
                config.system_prompt = system_prompt
                config.temperature = temperature
                config.max_tokens = max_tokens
                config.version += 1
            else:
                config = AgentConfigRecord(
                    agent_role=agent_role,
                    system_prompt=system_prompt,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    version=1
                )
                session.add(config)
            
            session.commit()
            self.clear_cache() # Invalidate cache on update
            logger.info(f"✓ Agent config persisted | Role: {agent_role} | Version: {config.version}")
            return config.version
        except Exception as e:
            session.rollback()
            logger.error(f"❌ Failed to save agent config for {agent_role}: {str(e)}")
            raise
        finally:
            session.close()

    def rollback_agent_config(self, agent_role: str):
        """Simplified rollback: resets configuration to system defaults or previous version logic."""
        # In a full implementation, this would query an 'AgentConfigHistory' table.
        # For now, it marks a need for manual reset or reverts to version 1 if applicable.
        logger.warning(f"Rollback requested for {agent_role}. Detailed versioning history not yet implemented.")
        # Placeholder for actual rollback logic
        return False

    # ==================== Phase 7.2: Execution Metrics Methods ====================

    def store_execution_metrics(self, task_id: str, metrics_data: dict) -> str:
        """Stores execution metrics for a completed step (Phase 7.2 Meta-Brain)."""
        session = self.Session()
        try:
            metric = ExecutionMetricsRecord(
                metric_id=str(uuid.uuid4()),  # Generate unique metric ID
                task_id=task_id,
                step_number=metrics_data.get('step_number'),
                agent_role=metrics_data.get('agent_role'),
                action=metrics_data.get('action'),
                duration_seconds=metrics_data.get('duration_seconds', 0.0),
                prompt_tokens=metrics_data.get('prompt_tokens', 0),
                completion_tokens=metrics_data.get('completion_tokens', 0),
                total_tokens=metrics_data.get('total_tokens', 0),
                success=metrics_data.get('success', False),
                dependencies=metrics_data.get('dependencies', []),
                parallelizable_with=metrics_data.get('parallelizable_with', []),
                meta=metrics_data.get('meta', {})
            )
            session.add(metric)
            session.commit()
            metric_id = metric.metric_id
            session.close()
            return metric_id
        except Exception as e:
            session.close()
            logger.error(f"Failed to store execution metrics: {e}")
            return None

    def get_execution_metrics_for_dag(self, dag_id: str, limit: int = 100) -> list:
        """Retrieves historical execution metrics for a DAG (Phase 7.2 Meta-Brain)."""
        session = self.Session()
        try:
            metrics = session.query(ExecutionMetricsRecord)\
                .filter(ExecutionMetricsRecord.task_id.like(f"{dag_id}%"))\
                .order_by(ExecutionMetricsRecord.created_at.desc())\
                .limit(limit).all()
            
            result = []
            for m in metrics:
                result.append({
                    'task_id': m.task_id,
                    'step_number': m.step_number,
                    'agent_role': m.agent_role,
                    'action': m.action,
                    'duration_seconds': m.duration_seconds,
                    'prompt_tokens': m.prompt_tokens,
                    'completion_tokens': m.completion_tokens,
                    'total_tokens': m.total_tokens,
                    'success': m.success,
                    'dependencies': m.dependencies,
                    'parallelizable_with': m.parallelizable_with,
                    'created_at': m.created_at.isoformat() if m.created_at else None
                })
            session.close()
            return result
        except Exception as e:
            session.close()
            logger.error(f"Failed to retrieve execution metrics: {e}")
            return []

    def store_dag_optimization(self, optimization_data: dict) -> str:
        """Stores a DAG optimization suggestion (Phase 7.2 Meta-Brain)."""
        session = self.Session()
        try:
            optimization = DAGOptimizationRecord(
                optimization_id=optimization_data.get('optimization_id', str(uuid.uuid4())),
                dag_id=optimization_data.get('dag_id', ''),
                optimization_type=optimization_data.get('optimization_type'),
                current_order=optimization_data.get('current_order'),
                suggested_order=optimization_data.get('suggested_order'),
                reason=optimization_data.get('reason'),
                estimated_speedup=optimization_data.get('estimated_speedup', 0.0),
                estimated_token_savings=optimization_data.get('estimated_token_savings', 0),
                confidence=optimization_data.get('confidence', 0.0),
                success_history=optimization_data.get('success_history', 0),
                applied=optimization_data.get('applied', False)
            )
            session.add(optimization)
            session.commit()
            opt_id = optimization.optimization_id
            session.close()
            return opt_id
        except Exception as e:
            session.close()
            logger.error(f"Failed to store DAG optimization: {e}")
            return None

    def get_dag_optimizations(self, dag_id: str, limit: int = 10) -> list:
        """Retrieves suggested optimizations for a DAG (Phase 7.2 Meta-Brain)."""
        session = self.Session()
        try:
            optimizations = session.query(DAGOptimizationRecord)\
                .filter(DAGOptimizationRecord.dag_id == dag_id)\
                .order_by(DAGOptimizationRecord.confidence.desc())\
                .limit(limit).all()
            
            result = []
            for opt in optimizations:
                result.append({
                    'optimization_id': opt.optimization_id,
                    'optimization_type': opt.optimization_type,
                    'current_order': opt.current_order,
                    'suggested_order': opt.suggested_order,
                    'reason': opt.reason,
                    'estimated_speedup': opt.estimated_speedup,
                    'estimated_token_savings': opt.estimated_token_savings,
                    'confidence': opt.confidence,
                    'success_history': opt.success_history,
                    'applied': opt.applied,
                    'created_at': opt.created_at.isoformat() if opt.created_at else None
                })
            session.close()
            return result
        except Exception as e:
            session.close()
            logger.error(f"Failed to retrieve DAG optimizations: {e}")
            return []

    # ==================== Phase 7.3: User Preference Methods ====================

    def save_user_preference(self, user_id: str, category: str, key: str, value: str):
        """Saves or updates a user preference."""
        session = self.Session()
        try:
            # Check if preference already exists
            pref = session.query(UserPreference).filter(
                UserPreference.user_id == user_id,
                UserPreference.preference_key == key
            ).first()

            if pref:
                pref.preference_value = value
                pref.updated_at = datetime.now()
            else:
                pref = UserPreference(
                    user_id=user_id,
                    category=category,
                    preference_key=key,
                    preference_value=value
                )
                session.add(pref)
            
            session.commit()
            session.close()
        except Exception as e:
            session.close()
            logger.error(f"Failed to save user preference: {e}")

    def get_user_preferences(self, user_id: str, category: Optional[str] = None) -> Dict[str, str]:
        """Retrieves all preferences for a user, optionally filtered by category."""
        session = self.Session()
        try:
            query = session.query(UserPreference).filter(UserPreference.user_id == user_id)
            if category:
                query = query.filter(UserPreference.category == category)
            
            prefs = query.all()
            result = {p.preference_key: p.preference_value for p in prefs}
            session.close()
            return result
        except Exception as e:
            session.close()
            logger.error(f"Failed to retrieve user preferences: {e}")
            return {}
